networks:
  shared_network:
    external: true
    name: kafka-network

services:
  order-api:
    build:
      context: ../order-api
      dockerfile: Dockerfile
    container_name: order-api
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - shared_network
